version: '3.8'
services:
  user-service:
    build:
      context: ./docker/user-service
    ports:
      - "3000:3000"

  product-service:
    build:
      context: ./docker/product-service
    ports:
      - "3001:3001"

  order-service:
    build:
      context: ./docker/order-service
    ports:
      - "3002:3002"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3333:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  grafana-storage:
