global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'microservices'
    static_configs:
      - targets:
          - 'user-service:3000'
          - 'product-service:3001'
          - 'order-service:3002'